<?php

declare(strict_types=1);

namespace Src\Modules\ScopeSheets\Tests\Unit\Domain;

use InvalidArgumentException;
use PHPUnit\Framework\TestCase;
use Src\Modules\ScopeSheets\Domain\Entities\ScopeSheet;
use Src\Modules\ScopeSheets\Domain\ValueObjects\ScopeSheetId;

final class ScopeSheetEntityTest extends TestCase
{
    public function test_create_builds_valid_scope_sheet(): void
    {
        $id = ScopeSheetId::generate();

        $sheet = ScopeSheet::create(
            id: $id,
            claimId: 1,
            generatedBy: 2,
            createdAt: '2026-03-31T00:00:00+00:00',
            scopeSheetDescription: 'Test description',
        );

        $this->assertSame($id, $sheet->id());
        $this->assertSame(1, $sheet->claimId());
        $this->assertSame(2, $sheet->generatedBy());
        $this->assertSame('Test description', $sheet->scopeSheetDescription());
        $this->assertNull($sheet->deletedAt());
    }

    public function test_create_throws_when_claim_id_is_zero(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Claim ID must be a positive integer.');

        ScopeSheet::create(
            id: ScopeSheetId::generate(),
            claimId: 0,
            generatedBy: 1,
            createdAt: '2026-03-31T00:00:00+00:00',
        );
    }

    public function test_create_throws_when_generated_by_is_zero(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Generated by user ID must be a positive integer.');

        ScopeSheet::create(
            id: ScopeSheetId::generate(),
            claimId: 1,
            generatedBy: 0,
            createdAt: '2026-03-31T00:00:00+00:00',
        );
    }

    public function test_update_changes_description_and_updated_at(): void
    {
        $sheet = ScopeSheet::create(
            id: ScopeSheetId::generate(),
            claimId: 1,
            generatedBy: 2,
            createdAt: '2026-03-31T00:00:00+00:00',
            scopeSheetDescription: 'Old description',
        );

        $sheet->update(
            scopeSheetDescription: 'New description',
            updatedAt: '2026-04-01T00:00:00+00:00',
        );

        $this->assertSame('New description', $sheet->scopeSheetDescription());
        $this->assertSame('2026-04-01T00:00:00+00:00', $sheet->updatedAt());
    }

    public function test_reconstitute_populates_all_fields(): void
    {
        $id = ScopeSheetId::generate();

        $sheet = ScopeSheet::reconstitute(
            id: $id,
            claimId: 5,
            generatedBy: 3,
            createdAt: '2026-01-01T00:00:00+00:00',
            updatedAt: '2026-02-01T00:00:00+00:00',
            deletedAt: '2026-03-01T00:00:00+00:00',
            scopeSheetDescription: 'Reconstituted',
        );

        $this->assertSame(5, $sheet->claimId());
        $this->assertSame(3, $sheet->generatedBy());
        $this->assertSame('2026-03-01T00:00:00+00:00', $sheet->deletedAt());
        $this->assertSame('Reconstituted', $sheet->scopeSheetDescription());
    }

    public function test_scope_sheet_id_value_object_equality(): void
    {
        $id1 = ScopeSheetId::generate();
        $id2 = ScopeSheetId::fromString($id1->toString());

        $this->assertTrue($id1->equals($id2));
    }

    public function test_scope_sheet_id_generates_unique_values(): void
    {
        $id1 = ScopeSheetId::generate();
        $id2 = ScopeSheetId::generate();

        $this->assertFalse($id1->equals($id2));
    }
}
