<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        @page { size: A4 landscape; margin: 18px 20px; }

        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            color: #1a1a2e;
            margin: 0;
            padding: 0;
        }

        .header-bar {
            background: linear-gradient(135deg, #0C2340 0%, #00B5E2 100%);
            color: #ffffff;
            padding: 12px 18px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 14px;
            border-radius: 6px;
        }

        .header-bar .brand {
            font-size: 18px;
            font-weight: bold;
            letter-spacing: 1px;
            color: #ffffff;
        }

        .header-bar .meta {
            font-size: 9px;
            color: rgba(255,255,255,0.85);
            text-align: right;
        }

        h1 {
            font-size: 14px;
            color: #0C2340;
            margin: 0 0 10px 0;
            border-bottom: 2px solid #00B5E2;
            padding-bottom: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        th {
            background-color: #0C2340;
            color: #ffffff;
            text-align: center;
            padding: 7px 6px;
            border: 1px solid #00B5E2;
            font-weight: bold;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        td {
            padding: 6px 6px;
            border: 1px solid #d1e8f5;
            text-align: center;
            vertical-align: middle;
            font-size: 9px;
        }

        tr:nth-child(even) td {
            background-color: #f0f7fc;
        }

        tr:nth-child(odd) td {
            background-color: #ffffff;
        }

        .badge-active {
            background-color: #d1fae5;
            color: #065f46;
            padding: 2px 7px;
            border-radius: 10px;
            font-weight: bold;
            font-size: 8px;
        }

        .badge-suspended {
            background-color: #fee2e2;
            color: #991b1b;
            padding: 2px 7px;
            border-radius: 10px;
            font-weight: bold;
            font-size: 8px;
        }

        .no-records {
            text-align: center;
            padding: 20px;
            color: #7A8FA8;
            font-style: italic;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 8px;
            color: #7A8FA8;
            text-align: center;
            padding: 6px 0;
            border-top: 1px solid #d1e8f5;
        }
    </style>
</head>
<body>

    <div class="header-bar">
        <div class="brand">&#9670; AquaShield CRM</div>
        <div class="meta">
            {{ $title }}<br>
            Generated: {{ $generatedAt }}
        </div>
    </div>

    <h1>Scope Sheets — Administrative Report</h1>

    <table>
        <thead>
            <tr>
                <th>Claim Internal ID</th>
                <th>Claim Number</th>
                <th>Description</th>
                <th>Generated By</th>
                <th>Presentations</th>
                <th>Zones</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    <td>{{ $row['claim_internal_id'] }}</td>
                    <td>{{ $row['claim_number'] }}</td>
                    <td style="text-align: left; max-width: 160px;">{{ $row['scope_sheet_description'] }}</td>
                    <td>{{ $row['generated_by_name'] }}</td>
                    <td>{{ $row['presentations_count'] }}</td>
                    <td>{{ $row['zones_count'] }}</td>
                    <td>
                        @if ($row['status'] === 'Active')
                            <span class="badge-active">Active</span>
                        @else
                            <span class="badge-suspended">Suspended</span>
                        @endif
                    </td>
                    <td>{{ $row['created_at'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="no-records">No scope sheets found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        AquaShield CRM &mdash; Confidential &mdash; {{ $generatedAt }}
    </div>

</body>
</html>
