<?php

declare(strict_types=1);

namespace Src\Modules\ScopeSheets\Infrastructure\Http\Export;

use Illuminate\Database\Eloquent\Builder;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Src\Modules\ScopeSheets\Application\DTOs\ScopeSheetFilterData;

final class ScopeSheetExcelExport implements FromQuery, WithHeadings, WithMapping, ShouldAutoSize
{
    use Exportable;

    public function __construct(
        private readonly ScopeSheetFilterData $filters,
    ) {}

    public function query(): Builder
    {
        return ScopeSheetExportQuery::build($this->filters);
    }

    public function headings(): array
    {
        return [
            'UUID',
            'Claim Internal ID',
            'Claim Number',
            'Description',
            'Generated By',
            'Presentations',
            'Zones',
            'Status',
            'Created At',
            'Deleted At',
        ];
    }

    public function map(mixed $sheet): array
    {
        return ScopeSheetExportTransformer::transformForExcel($sheet);
    }
}
