<?php

declare(strict_types=1);

namespace Src\Modules\ScopeSheets\Domain\Entities;

use InvalidArgumentException;
use Src\Modules\ScopeSheets\Domain\ValueObjects\ScopeSheetId;

final class ScopeSheet
{
    private function __construct(
        private ScopeSheetId $id,
        private int $claimId,
        private int $generatedBy,
        private ?string $scopeSheetDescription,
        private string $createdAt,
        private string $updatedAt,
        private ?string $deletedAt,
    ) {}

    public static function create(
        ScopeSheetId $id,
        int $claimId,
        int $generatedBy,
        string $createdAt,
        ?string $scopeSheetDescription = null,
    ): self {
        if ($claimId <= 0) {
            throw new InvalidArgumentException('Claim ID must be a positive integer.');
        }

        if ($generatedBy <= 0) {
            throw new InvalidArgumentException('Generated by user ID must be a positive integer.');
        }

        return new self(
            id: $id,
            claimId: $claimId,
            generatedBy: $generatedBy,
            scopeSheetDescription: $scopeSheetDescription,
            createdAt: $createdAt,
            updatedAt: $createdAt,
            deletedAt: null,
        );
    }

    public static function reconstitute(
        ScopeSheetId $id,
        int $claimId,
        int $generatedBy,
        string $createdAt,
        string $updatedAt,
        ?string $deletedAt = null,
        ?string $scopeSheetDescription = null,
    ): self {
        return new self(
            id: $id,
            claimId: $claimId,
            generatedBy: $generatedBy,
            scopeSheetDescription: $scopeSheetDescription,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
            deletedAt: $deletedAt,
        );
    }

    public function update(
        ?string $scopeSheetDescription,
        string $updatedAt,
    ): void {
        $this->scopeSheetDescription = $scopeSheetDescription;
        $this->updatedAt = $updatedAt;
    }

    public function id(): ScopeSheetId { return $this->id; }
    public function claimId(): int { return $this->claimId; }
    public function generatedBy(): int { return $this->generatedBy; }
    public function scopeSheetDescription(): ?string { return $this->scopeSheetDescription; }
    public function createdAt(): string { return $this->createdAt; }
    public function updatedAt(): string { return $this->updatedAt; }
    public function deletedAt(): ?string { return $this->deletedAt; }
}
